name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Trigger Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Hook
        run: |
          curl -f -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
